# Generated by Django 3.1.1 on 2020-09-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200921_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
